### ISSUE TITLE
Can't install ahk latest version (2.0.9)

### ISSUE THREAD

**Issue by edwyn-amador** [AutoHotkey/AutoHotkeyUX#13] opened 2023-09-19 21:10 UTC
Please see the following screenshot as reference:

![image](https://github.com/AutoHotkey/AutoHotkeyUX/assets/36249854/2b123fec-06e6-4ac4-9338-4c034383712c)

Error: Failed

Specifically: 1

    1155: If destDir != ""
    1156: DirCreate(destDir)
▶    1157: FileMove(sourcePath, destPath)
    1158: Try
    1158: this.Hashes.Delete(sourcePath)

**Comment by Lexikos** [comment] 2023-09-20 11:05
More work could be done on error handling or error reporting (to give detail about why this failed), but ultimately, the cause is likely to be something in your environment, outside the installer's control, such as an antivirus product, disk error, or script it couldn't close.

There are no changes to the UX scripts between v2.0.7 and v2.0.9.

**Comment by edwyn-amador** [comment] 2023-09-20 11:27
@Lexikos I thought that screenshot would be enough, but yes, you're right, for context I've tried with my antivirus disabled (Avast) and doesn't work either also restarted the OS, with v2.0.7 installer doesn't show up any error/warning window but still doesn't install it nor open the Autohotkey Dash either due to same, but I don't have issues with the v2.0.8 installer, however I can install v2.0.6 and v2.0.7 on the Windows Sandbox environment so I am not sure what could be the cause but every kind of antivirus protection is disabled, I will try restarting the OS in safe mode and see what happens but it is weird for me that I don't have issues at all with the v2.0.8 installer.

**Comment by edwyn-amador** [comment] 2023-09-20 11:33
@Lexikos  So I confirm the issue still happens even in Safe Mode

> but I don't have issues with the v2.0.8 installer

Maybe this information can help in order for you to get what could be the cause?

**Comment by Lexikos** [comment] 2023-09-20 12:01
There should be a directory named `.staging` in the destination directory while the error dialog is visible. It will contain any files that have been extracted but not yet moved by the install script. A listing of the remaining files should indicate which file is failing to be moved.

> every kind of antivirus protection is disabled

In my experience, disabling an antivirus program is insufficient to exclude it as the cause of an issue. A disabled antivirus generally still has drivers present and loaded, though maybe not in safe mode.

**Comment by edwyn-amador** [comment] 2023-09-20 14:33
So the files inside the `.staging` folder  are all the ones listed when extracting `AutoHotkey_2.0.9.zip` so it doesn't move any file at all.

Btw, I just remembered that I had an issue with the FileMove command before, just don't remember starting from which AHK version nor what kind of prompt it was showing but most probably the same as it was getting to an expection while trying to move the files so I had to update my script to use FileCopy and then FileDelete instead. Maybe this other information can be of help? It seems some change on the FileMove command in those (v2.0.7 and v2.0.9) installers has affected in my end while I am not having this issue with the FileMove command from the v2.0.8 installer.

**Comment by edwyn-amador** [comment] 2023-09-20 14:40
@Lexikos Also as a workaround for now, would it be a safe installation if I just replace those files under their corresponding location for the moment? As I'm not sure if there would be some kind of registry leftover conflicting with the current installed version or something relevant.

**Comment by Lexikos** [comment] 2023-10-07 03:42
There has been no change to the FileMove *function*, as the commit history and `git blame`/`git gui blame` will attest. However, the signature of the binary changes with every release, and this can affect the behaviour of antivirus software.

Installer behaviour depends on whether the version you are installing is newer or older than the version already installed (usually read from `HKLM\Software\AutoHotkey`). If the installed version is newer, the version you are installing is installed into its own subdirectory based on the version number, and the installed UX scripts are not changed. Otherwise, it is installed into "v2" and any existing file which does not have the same version number is "displaced" (moved into a subdirectory based on its version number) instead of being overwritten.

FileMove usually works on an exe file even if it is running, but it may fail if there are other open handles to the file.

The presence of DisplaceFile in the call stack in your screenshot indicates that the version you are installing is newer than the version recorded in the registry. We can also assume that there are files in the "v2" directory which are not the same version as what you are installing, otherwise DisplaceFile would not be called.

If you first uninstall whatever version is in the "v2" folder, DisplaceFile will not be called. If you reinstall that version afterward, it will be installed into its own subdirectory (assuming the version you install into "v2" is newer).

---

Replacing files without updating the hashes in `installedfiles.csv` would prevent the uninstaller from removing those files, by design.

---

If you use FileCopy and then FileDelete, there will be a delay while the file is copied, before FileDelete is called. If an external process has locked the file, the delay may allow it to finish whatever it is doing and close the file.

FileMove usually preserves the permissions of the source file instead of inheriting from the destination directory, whereas I think CopyFile always does the latter. It shouldn't matter in this case because the source directory is a (usually new) subdirectory of the destination.

**Comment by edwyn-amador** [comment] 2023-10-27 22:32
Thanks for your detailed answer @Lexikos , I had to do the adjustments manually in order to be able to have the latest version installed

**Closed as not planned** 2024-03-23 00:08 UTC
